SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE hourly_rate_history;
TRUNCATE TABLE payroll_payments;
TRUNCATE TABLE shift_assignments;
TRUNCATE TABLE shift_templates;
TRUNCATE TABLE work_shifts;
TRUNCATE TABLE stock_movements;
TRUNCATE TABLE stock_receipt_details;
TRUNCATE TABLE stock_receipts;
TRUNCATE TABLE product_recipes;
TRUNCATE TABLE ingredients;
TRUNCATE TABLE ingredient_categories;
TRUNCATE TABLE suppliers;
TRUNCATE TABLE invoice_details;
TRUNCATE TABLE invoices;
TRUNCATE TABLE promotions;
TRUNCATE TABLE products;
TRUNCATE TABLE categories;
TRUNCATE TABLE tables;
TRUNCATE TABLE areas;
TRUNCATE TABLE employees;
TRUNCATE TABLE accounts;
TRUNCATE TABLE roles;
SET FOREIGN_KEY_CHECKS=1;
